# D:\Proyectos\asaieexodo_backend_update\docker\nginx\nginx.conf
server {
    listen 80; # Nginx escuchará en el puerto 80 interno del contenedor
    index index.php index.html;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html/public; # Apunta al directorio 'public' de Laravel

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000; # Envía las peticiones PHP al servicio 'app' (PHP-FPM) en su puerto 9000
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string; # Reglas para URLs amigables de Laravel
        gzip_static on;
    }
}s
