Ext.define('Admin.model.docentes.observador.ObservadorModel', {
   extend: 'Admin.model.base.BaseModel',
   fields: [
		{ name: 'id'},
		{ name: 'año'},
		{ name: 'id_matric'},
		{ name: 'vision'},
		{ name: 'audicion'},
		{ name: 'limit_fisicas'},
		{ name: 'enfer_recurentes'},
		{ name: 'comp_academico'},
		{ name: 'comp_disciplinario'},
		{ name: 'vive_con'},
		{ name: 'numero_hnos'},
		{ name: 'lugar_hnos'},
		{ name: 'hnos_bachilleres'},
		{ name: 'condicion_economica'},
		{ name: 'relacion_madre'},
		{ name: 'relacion_padre'},
		{ name: 'relacion_hnos'},
		{ name: 'n_personas_vive'},
		{ name: 'dis_aprox_col'},
		{ name: 'tiempo_llegada_col'},
		{ name: 'transporte'},
		{ name: 'vivienda'},
		{ name: 'luz'},
		{ name: 'movil'},
		{ name: 'acueducto'},
		{ name: 'alcantarillado'},
		{ name: 'equipo_sonido'},
		{ name: 'television' },
		{ name: 'computadora'},
		{ name: 'pregunta1'},
		{ name: 'pregunta2'},
		{ name: 'cual_positivas'},
		{ name: 'cual_negativas'},
		{ name: 'estado'},
		{ name: 'talla'},
		{ name: 'peso'},
		{ name: 'religion'},
		{ name: 'deporte'},
		{ name: 'musica'},
		{ name: 'arte'},
		{ name: 'comida'},
		{ name: 'prof_oficio'},
		{ name: 'motricidad_fina'},
		{ name: 'motricidad_gruesa'},
		{ name: 'temporo_espacial'},
		{ name: 'actitud_verval'},
		{ name: 'artitud_numerica'},
		{ name: 'liderazgo'},
		{ name: 'comportamiento'},
		{ name: 'dislexia'},
		{ name: 'disortografia'},
	    { name: 'discalculia'},
     	{ name: 'fecha'}
     ]
});