SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

ALTER TABLE `establecimiento`
	CHANGE COLUMN `ID` `id` INT NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `ID_COUNTRY` `country_id` INT NOT NULL DEFAULT '45' AFTER `id`,
	CHANGE COLUMN `ID_CITY` `city_id` INT NOT NULL AFTER `country_id`,
	CHANGE COLUMN `COD_DANE` `school_id` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_general_ci' AFTER `city_id`,
	CHANGE COLUMN `NOMBRE_IE` `school_name` VARCHAR(250) NOT NULL COLLATE 'utf8_general_ci' AFTER `school_id`,
	CHANGE COLUMN `NIT` `dni` VARCHAR(20) NULL COLLATE 'utf8_general_ci' AFTER `school_name`,
	CHANGE COLUMN `NOMBRE_RECTOR` `director_name` VARCHAR(100) NULL COLLATE 'utf8_general_ci' AFTER `dni`,
	CHANGE COLUMN `BARRIO` `suburd` VARCHAR(50) NULL COLLATE 'utf8_general_ci' AFTER `director_name`,
	CHANGE COLUMN `DIRECCION` `address` VARCHAR(100) NULL COLLATE 'utf8_general_ci' AFTER `suburd`,
	CHANGE COLUMN `LOCALIDAD` `location` VARCHAR(100) NULL COLLATE 'utf8_general_ci' AFTER `address`,
	CHANGE COLUMN `TELEFONOS` `phones` VARCHAR(250) NULL DEFAULT '0' COLLATE 'utf8_general_ci' AFTER `location`,
	CHANGE COLUMN `WEB` `web` VARCHAR(50) NULL COLLATE 'utf8_general_ci' AFTER `phones`,
	CHANGE COLUMN `CORREO` `email` VARCHAR(200) NULL COLLATE 'utf8_general_ci' AFTER `web`,
	CHANGE COLUMN `SEDES` `number_locations` SMALLINT NOT NULL DEFAULT 1 AFTER `email`,
	DROP COLUMN `ID_ZONA`,
	DROP COLUMN `ID_SECTOR`,
	DROP COLUMN `TIPO_EST`,
	DROP COLUMN `PROPIEDAD_PLANTA_FIS`,
	DROP COLUMN `GENERO`,
	DROP COLUMN `COD_PROP`,
	DROP COLUMN `FAX`,
	DROP COLUMN `NUCLEO`,
	DROP INDEX `COD_SEX`,
	DROP INDEX `COD_ZONA`,
	DROP INDEX `COD_PROP`,
	DROP INDEX `COD_SEC`,
	DROP INDEX `NUCLEO`,
	DROP INDEX `TIPO_ESTAB`,
	DROP INDEX `COD_DANE`,
	DROP INDEX `K_ID_COUNTRY`,
	DROP INDEX `K_ID_CITY`,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`) USING BTREE,
	DROP FOREIGN KEY `FK_establecimiento_cities`,
	DROP FOREIGN KEY `FK_establecimiento_countries`;


RENAME TABLE `establecimiento` TO `school`;

ALTER TABLE `school`
	ADD INDEX `country_id` (`country_id`),
	ADD INDEX `city_id` (`city_id`),
	ADD CONSTRAINT `FK_school_countries` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
	ADD CONSTRAINT `FK_school_cities` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE `sedes`
	CHANGE COLUMN `ID` `id` INT NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `ID_CITY` `city_id` INT NOT NULL AFTER `id`,
	CHANGE COLUMN `ID_ZONA` `zone_id` SMALLINT NOT NULL DEFAULT 1 AFTER `city_id`,
	CHANGE COLUMN `ID_SEXO` `sex_id` SMALLINT NOT NULL DEFAULT 1 AFTER `zone_id`,
	CHANGE COLUMN `NOMBRE_SEDE` `headquarters_name` VARCHAR(100) NULL COLLATE 'utf8_general_ci' AFTER `sex_id`,
	CHANGE COLUMN `DIRECCION_SEDE` `address` VARCHAR(100) NULL COLLATE 'utf8_general_ci' AFTER `headquarters_name`,
	CHANGE COLUMN `TELEFONOS_SEDE` `phones` VARCHAR(200) NULL COLLATE 'utf8_general_ci' AFTER `address`,
	CHANGE COLUMN `BARRIO` `suburd` VARCHAR(50) NULL COLLATE 'utf8_general_ci' AFTER `phones`,
	CHANGE COLUMN `EMAIL` `email` VARCHAR(200) NULL COLLATE 'utf8_general_ci' AFTER `suburd`,
	CHANGE COLUMN `PRINCIPAL` `is_main` VARCHAR(10) NULL COLLATE 'utf8_general_ci' AFTER `email`,
	ADD COLUMN `state` SMALLINT(1) NOT NULL DEFAULT 1 AFTER `is_main`,
	DROP COLUMN `ID_INST`,
	DROP COLUMN `CONS_SEDE`,
	DROP COLUMN `COD_DANE`,
	DROP COLUMN `DANE_SEDE`,
	DROP COLUMN `FAX`,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`) USING BTREE,
	DROP INDEX `COD_ZONA`,
	ADD INDEX `COD_ZONA` (`zone_id`) USING BTREE,
	DROP INDEX `COD_SEXO`,
	ADD INDEX `COD_SEXO` (`sex_id`) USING BTREE,
	DROP INDEX `mun`,
	ADD INDEX `mun` (`city_id`) USING BTREE;

ALTER TABLE `sedes`
	ADD CONSTRAINT `FK_sedes_cities` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE `zona`
	COLLATE='utf8mb4_general_ci',
	CONVERT TO CHARSET utf8mb4;

ALTER TABLE `zona`
	CHANGE COLUMN `tipo` `zone_name` VARCHAR(15) NOT NULL COLLATE 'utf8mb4_general_ci' AFTER `id_zona`;

    ALTER TABLE `school`
	CHANGE COLUMN `suburd` `suburb` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci' AFTER `director_name`;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
