Ext.define('Admin.model.docentes.NotasModel', {
    extend: 'Admin.model.base.BaseModel',
    fields: [
		{ name	: 'nombres'},
		{ name	: 'id_curso'},
		{ name	: 'id_grado'},
		{ name	: 'id_matric'},
		{ name	: 'id_jorn'},
		{ name	: 'grupo'},
		{ name	: 'id_group'},
		{ name	: 'id_grupo'},
		{ name	: 'periodo'},
		{ name	: 'asignatura'},
		{ name	: 'year'},
		{ name	: 'n1',type	: 'float'},
		{ name	: 'n2',type	: 'float'},
		{ name	: 'n3',type	: 'float'},
		{ name	: 'n4',type	: 'float'},
		{ name	: 'n5',type	: 'float'},
		{ name	: 'n6',type	: 'float'},
		{ name	: 'n7',type	: 'float'},
		{ name	: 'n8',type	: 'float'},
		{ name	: 'n9',type	: 'float'},
		{ name	: 'n10',type	: 'float'},
		{ name	: 'n11',type	: 'float'},
		{ name	: 'n12',type	: 'float'},
		{ name	: 'n13',type	: 'float'},
		{ name	: 'n14',type	: 'float'},
		{ name	: 'n15',type	: 'float'},
		{ name	: 'n16',type	: 'float'},
		{ name	: 'n17',type	: 'float'},
		{ name	: 'n18',type	: 'float'},
		{ name	: 'n19',type	: 'float'},
		{ name	: 'n20',type	: 'float'},
		{ name	: 'n21',type	: 'float'},
		{ name	: 'n22',type	: 'float'},
		{ name	: 'n23',type	: 'float'},
		{ name	: 'n24',type	: 'float'},
		{ name	: 'n25',type	: 'float'},
		{ name	: 'n26',type	: 'float'},
		{ name	: 'n27',type	: 'float'},
		{ name	: 'n28',type	: 'float'},
		{ name	: 'n29',type	: 'float'},
		{ name	: 'n30',type	: 'float'},
		{ name	: 'final',type	: 'float'},
		{ name	: 'conceptual'},
		{ name	: 'prom'},
		{ name	: 'faltas', type : 'int'},
		{ name	: 'injustificadas', type : 'int'},
		{ name	: 'retraso', type : 'int'},
        { name	: 'nivelacion', type : 'bool'}
   	]
});
